(lambda (a b)
  (assure <integer> a)
  (assure <integer> b)
  (cond
    ((= a 0) 0)
    ((= b 0) 0)
    (t (let* ((r (* (div a (gcd a b)) b)))
         (if (< r 0)
           (- 0 r)
           r)))))
