(lambda-macro (newvalue seq &rest z)
  (let ((_newvalue (gensym)))
    `(if (basic-array-p ,seq)
       (set-aref ,newvalue ,seq ,@z)
       (let ((,_newvalue ,newvalue))
         (setf ,seq (swap-elt ,_newvalue ,seq ,@z))
         ,_newvalue))))
