(lambda-macro (newvalue seq &rest z)
  (let ((_newvalue (gensym)))
    `(if (general-array-p ,seq)
       (set-garef ,newvalue ,seq ,@z)
       (let ((,_newvalue ,newvalue))
         (setf ,seq (swap-elt ,_newvalue ,seq ,@z))
         ,_newvalue))))
