;;; test for (rune)
(assert-eq (char< #\a #\b) t)
(assert-eq (char> #\a #\b) nil)
(assert-eq (char<= #\a #\b) t)
(assert-eq (char>= #\a #\b) nil)
(assert-eq (char= #\a #\b) nil)
(assert-eq (char/= #\a #\b) t)

(assert-eq (characterp #\a) t)
(assert-eq (characterp 'a) nil)
(assert-eq (characterp "2") nil)

(assert-eq (char-index #\b "abcab"  ) 1)
(assert-eq (char-index #\B "abcab"  ) nil)
(assert-eq (char-index #\b "abcab" 2) 4)
(assert-eq (char-index #\d "abcab"  ) nil)
