;;; test for (string<=>)
(assert-eq (string< "a" "b") t)
(assert-eq (string> "a" "b") nil)
(assert-eq (string<= "a" "b") t)
(assert-eq (string>= "a" "b") nil)
(assert-eq (string= "a" "b") nil)
(assert-eq (string/= "a" "b") t)
