package gmnlisp

import (
	"testing"
)

func TestOperators(t *testing.T) {
	evalTest(t, "(+ 1 2)", Integer(3))
	evalTest(t, "(+ 1 2 3)", Integer(6))
	evalTest(t, "(- 10 9)", Integer(1))
	evalTest(t, "(- 10 1 2)", Integer(7))
	evalTest(t, "(* 1 2)", Integer(2))
	evalTest(t, "(* 1 2 3)", Integer(6))
	evalTest(t, "(/ 6 2)", Integer(3))
	evalTest(t, `(+ "1" "2")`, String("12"))
	evalTest(t, `(> 2 1.0)`, True)
	evalTest(t, `(> 2.0 3)`, Null)
	evalTest(t, `(< 2.0 3)`, True)
	evalTest(t, `(< 2 1.0)`, Null)
	evalTest(t, `(<= 2.0 3)`, True)
	evalTest(t, `(<= 3 3)`, True)
	evalTest(t, `(<= 4 3)`, Null)
	evalTest(t, `(>= 2.0 3)`, Null)
	evalTest(t, `(>= 3 3)`, True)
	evalTest(t, `(>= 4 3)`, True)
	evalTest(t, `(> "a" "b")`, Null)
	evalTest(t, `(< "a" "b" "c")`, True)
	evalTest(t, `(< 1 2 3)`, True)
	evalTest(t, `(< 1 2 1)`, Null)
	evalTest(t, `(>= 3 2 2)`, True)
	evalTest(t, `(>= 2 2 2)`, True)
	evalTest(t, `(> 3 2 1)`, True)
	evalTest(t, `(= 1 1)`, True)
	evalTest(t, `(= 1.0 1)`, True)
	evalTest(t, `(= 1 1.0)`, True)
	evalTest(t, `(= 1.0 1.0)`, True)
	evalTest(t, `(= 1.0 1.0 1.0)`, True)
	evalTest(t, `(= 1 2)`, Null)
	evalTest(t, `(= 1 2.0)`, Null)
	evalTest(t, `(= 1.0 2)`, Null)
	evalTest(t, `(= 1 2.0)`, Null)
	evalTest(t, `(= "ABC" "abc")`, True)
	evalTest(t, `(= "ABC" "abcd")`, Null)
	evalTest(t, `(equalp "DEF" "defg")`, Null)
	evalTest(t, `(equalp "GHQ" "ghq")`, True)
	evalTest(t, `(equalp (cons 1 (cons 2 nil)) '(1 2))`, True)
	evalTest(t, `(equalp (cons 1 2) '(1))`, Null)
}
