;; test for (find-all-string-submatch)
(test (=~ "a(x*)b" "-ab-") '(("ab" "")))
(test (=~ "a(x*)b" "-axxb-") '(("axxb" "xx")))
(test (=~ "a(x*)b" "-ab-axb-") '(("ab" "")("axb" "x")))
(test (=~ "a(x*)b" "-axxb-ab-") '(("axxb" "xx") ("ab" "")))

;; test for (find-all-string-submatch-index)
(test (=~i "a(x*)b" "-ab-") '((1 3 2 2)))
(test (=~i "a(x*)b" "-axxb-") '((1 5 2 4)))
(test (=~i "a(x*)b" "-ab-axb-") '((1 3 2 2)(4 7 5 6)))
(test (=~i "a(x*)b" "-axxb-ab-") '((1 5 2 4)(6 8 7 7)))
