(defun set-nth (newvalue Z L)
  (set-elt newvalue L Z))
(defun set-nthcdr (newvalue z source)
  (let ((s source))
    (while s
           (setq z (1- z))
           (if (zerop z)
             (set-cdr newvalue s))
           (setq s (cdr s)))
    source))
